# Request Values
nav_msgs/Odometry pose # The initial state of the Robot.
geometry_msgs/PoseStamped goal # The Goal Pose

# AStar Configuration
float64 inflation_value  # Meters to inflate map by.
float64 epsilon # AStar Heuristic Inflation Value
float64 fixed_z # Fixed Z height. In the case of 3D planning, this is the height of the Goal.
uint8 use_3d # Flag indicating if planning should be done in the voxelized space.

# OPTIONAL FAS Parameters
uint8 use_fas # Flag indicating if the Fully Actuated System should be used for planning
float64 max_vel # Value for Maximum Velocity. Used only for FAS systems.
float64 max_acc # Value for Maximum Accleration. Used only for FAS systems.
float64 rho # Rho value for FAS systems.
float64 tau # Tau value for FAS systems

---
# Response Values
bool success
