# This represents a distance information vector used by reference governor
# dQgO  = distance between governor and obstacle space in Q norm
# dIgO  = distance between governor and obstacle space in Eculidean norm
# dIcO: Distance between governor cone and obstacle space in Eculidean norm
# dIrO = distance between robot and obstacle space in Eculidean norm

float32 dQcO
float32 dIgO
float32 dIcO
float32 dIrO
